name: build and update helm

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      # build & push to docker hub

      - name: Get latest tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pod-best-by:${{ steps.vars.outputs.tag }}

      # Trivy scan

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/pod-best-by:${{ steps.vars.outputs.tag }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always() 
        with:
          sarif_file: 'trivy-results.sarif'

      # Update helm chart

      - name: Update chart.yaml
        run: |
          sed 's/^appVersion: "[^"]*"/appVersion: "${{ steps.vars.outputs.tag }}"/' -i ./charts/bestby/Chart.yaml
          sed 's/^version: "[^"]*"/version: "${{ steps.vars.outputs.tag }}"/' -i ./charts/bestby/Chart.yaml

      # push changes

      - name: Push changes
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: '*.yaml'
          branch: master
          default_author: github_actions
          author_name: Jordi Prats
          author_email: jordi.prats@gmail.com
          committer_name: Jordi Prats
          committer_email: jordi.prats@gmail.com
          message: 'update helm chart to latest release'
          pull: 'NO-PULL'
          push: true
